//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProjet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detail_commande
    {
        public int id_commande { get; set; }
        public int id_produit { get; set; }
        public string prix_unit { get; set; }
        public int quantite { get; set; }
    }
}
