//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProjet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produit
    {
        public long id { get; set; }
        public string nom_produit { get; set; }
        public long id_categorie { get; set; }
        public string prix { get; set; }
        public string image { get; set; }
        public string description { get; set; }
        public long stock { get; set; }
        public int quantite_lots { get; set; }
        public int niveau_reapprovisionnement { get; set; }
    }
}
